### ISSUE TITLE
Is there a way to import markdown format or .md file

### ISSUE THREAD

**Issue by gjlmotea** [opdev1004/mdblogger#1]
Hello, I like this plug-in idea, it is simple and convenient to use.
Is there a way to import markdown format or .md file?

![image](https://github.com/opdev1004/mdblogger/assets/40420568/7004484d-1173-4cf3-bf0e-47317993fbf3)

Want it to support this feature.

**Comment by opdev1004** [comment]
Hi!

No, not yet. There's a way to do it. But I have to check if they allow it through the security rules and chrome's supported API.

Because I think it is better to be drag and drop or load/save button. But extensions are all web based, so I need to check if they allow that first.

But I am pretty sure I should be able to add that feature.

By the way, this update might take some time as i'm working on other things too.

**Comment by opdev1004** [comment]
The update of this is curently getting reviewed by chrome web store.
If there's no problem, it will be passed and I will push the changes and close this issue.

By the way, I did button version. And maybe drag and drop can be added lateer. So for now just buttons

**Comment by opdev1004** [comment]
done in version 0.0.2

**Comment by gjlmotea** [comment]
Thank you so much
This reduces the time I spend adjusting the format of posts.
